#!/usr/bin/env bash

if [ -f "/opt/mgweb/mapped/start" ]; then
  echo "Running user customisation start file"
  chmod +x /opt/mgweb/mapped/start
  /opt/mgweb/mapped/start
fi

nginx -c /etc/nginx/nginx.conf
echo "NGINX started"
service xinetd start
./ydb_run start^%zmgwebUtils
echo ""
echo "The mgweb Container is ready for use!"
echo ""
tail -f /var/log/nginx/access.log
